# Generated by Django 4.0 on 2022-02-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_driver_delete_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
