# Generated by Django 4.0 on 2022-02-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='dl_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
