# Generated by Django 4.0 on 2022-03-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer Not To Say')], default='P', max_length=1),
        ),
    ]
