# Generated by Django 4.0 on 2022-01-11 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=2)),
                ('nature', models.CharField(choices=[('F', 'fragile'), ('NF', 'Not Fragile')], help_text="What's the nature of your cargo?", max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name_plural': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'location',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_type', models.CharField(choices=[('L', 'Lorry'), ('P', 'Pickup'), ('B', 'MotorBike')], help_text='vehicle carriage type', max_length=100)),
                ('carrier_capacity', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], help_text='Approximate vehicle carrying capacity', max_length=100)),
                ('vehicle_registration_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(help_text='vehicle model type', max_length=100)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
            ],
            options={
                'verbose_name_plural': 'Vehicle',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('C', 'Canceled'), ('F', 'fulfilled')], default='P', max_length=1)),
                ('price', models.IntegerField(default=0)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.cargo')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dropoff', to='shipment.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup', to='shipment.location')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipment.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('shipment', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='CustomerShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment')),
            ],
            options={
                'unique_together': {('shipment', 'customer')},
            },
        ),
    ]
