# Generated by Django 4.0 on 2022-01-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='size',
            field=models.CharField(choices=[('L', 'Large'), ('S', 'Small'), ('M', 'Medium')], max_length=1),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='carrier_capacity',
            field=models.CharField(choices=[('L', 'Large'), ('S', 'Small'), ('M', 'Medium')], help_text='Approximate vehicle carrying capacity', max_length=100),
        ),
    ]
