# Generated by Django 4.0 on 2022-01-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_alter_cargo_size_alter_shipment_shipment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
