# Generated by Django 4.0 on 2022-01-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_location_alter_shipment_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
