# Generated by Django 4.0 on 2022-01-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_alter_location_lat_alter_location_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customershipment',
            name='order_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='price',
            field=models.IntegerField(),
        ),
    ]
