# Generated by Django 4.0 on 2022-01-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0006_customershipment_order_number_alter_shipment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customershipment',
            name='order_number',
        ),
        migrations.AddField(
            model_name='shipment',
            name='order_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
