# Generated by Django 4.0 on 2022-01-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0008_remove_shipment_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customershipment',
            name='order_number',
            field=models.CharField(max_length=10),
        ),
    ]
