# Generated by Django 4.0 on 2022-03-02 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_alter_driver_gender'),
        ('shipment', '0010_alter_vehicle_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='driver.vehicle'),
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
