# Generated by Django 4.0 on 2021-12-16 15:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=1)),
                ('nature', models.CharField(choices=[('F', 'fragile'), ('NF', 'Not Fragile'), ('HWC', 'Handle with care')], help_text='How fragile is your cargo', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Add name or a brief description of your package eg Animal,Building tools etc', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='CustomerShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_position', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat_position', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'destination',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_position', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat_position', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'origin',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_type', models.CharField(choices=[('L', 'Lorry'), ('P', 'Pickup'), ('B', 'MotorBike')], help_text='vehicle carriage type', max_length=100)),
                ('carrier_capacity', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], help_text='vehicle carrying capacity', max_length=100)),
                ('vehicle_registration_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(help_text='vehicle model type', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Vehicle',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'canceled'), ('F', 'fulfilled'), ('P', 'Pending'), ('A', 'active')], default='A', max_length=1)),
                ('shipment_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.cargo')),
                ('carriage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipment.vehicle')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipment.destination')),
            ],
        ),
    ]
