# Generated by Django 3.2.9 on 2021-12-07 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=1)),
                ('sensitivity', models.CharField(choices=[('F', 'fragile'), ('NF', 'Not Fragile'), ('HWC', 'Handle with care')], help_text='How fragile is your cargo', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='users.city')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='users.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
            options={
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_type', models.CharField(choices=[('L', 'Lorry'), ('P', 'Pickup'), ('B', 'MotorBike')], help_text='vehicle carriage type', max_length=100)),
                ('carrier_capacity', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], help_text='vehicle carrying capacity', max_length=100)),
                ('vehicle_registration_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(help_text='vehicle model type', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('arrival', models.DateTimeField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, default=0)),
                ('status', models.CharField(choices=[('C', 'canceled'), ('F', 'fulfilled'), ('A', 'active')], default='A', max_length=1)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.cargo')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.driver')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipment.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('C', 'canceled'), ('A', 'active'), ('F', 'fulfilled')], default='A', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipment.shipment')),
            ],
            options={
                'unique_together': {('shipment', 'customer')},
            },
        ),
    ]
