# Generated by Django 4.0 on 2021-12-17 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.cargo'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipment.destination'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipment.origin'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipment.vehicle'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipment.customershipment'),
        ),
        migrations.AddField(
            model_name='customershipment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='customershipment',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='customershipment',
            unique_together={('shipment', 'customer')},
        ),
    ]
