# Generated by Django 4.0 on 2021-12-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='lat_position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='long_position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='origin',
            name='lat_position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='origin',
            name='long_position',
            field=models.CharField(max_length=50),
        ),
    ]
