# Generated by Django 4.0 on 2021-12-22 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_alter_destination_lat_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='shipment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment'),
        ),
    ]
